### ISSUE TITLE
Please fix the product link & the wiki link, thanks <3

### ISSUE THREAD

**Issue by Zander-M** [DFRobot/DFRobot_RGBLCD#1]

**Comment by qsjhyy** [comment]
Hello, this repository has been renamed and updated (https://github.com/DFRobot/DFRobot_RGBLCD1602). Once the wiki link is redirected to this repository, it will be set as a private repository.

**Comment by qsjhyy** [comment]
Due to a lack of further communication for an extended period, this issue has been closed. If there is a need in the future, it can be reopened at any time.
